name: Servidor Actualizador Real

on:
  workflow_dispatch: # Activa el botón manual en la pestaña Actions

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar librerias y dependencias del sistema
        run: |
          pip install playwright beautifulsoup4 lxml firebase-admin
          python -m playwright install chromium
          # Comando crítico para instalar los componentes de Linux necesarios:
          python -m playwright install-deps chromium

      - name: Correr Extractor Oficial
        run: python animev1_tracker.py
 
